---
apiVersion: v1
kind: Namespace
metadata:
  name: test-persistence
---
apiVersion: v1
kind: LimitRange
metadata:
  name: test-persistence
spec:
  limits:
    - default:
        memory: 128Mi
      defaultRequest:
        memory: 128Mi
      type: Container
